<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
class S3DemoSeeder extends Seeder { public function run(){ $faker=Faker::create('ru_RU'); $userIds=DB::table('users')->pluck('id')->all(); if(count($userIds)<10){ foreach(range(1,100) as $i){ $id=DB::table('users')->insertGetId(['name'=>$faker->name(),'email'=>$faker->unique()->safeEmail(),'password'=>bcrypt('password'),'created_at'=>now(),'updated_at'=>now()]); $userIds[]=$id; } }
 foreach(range(1,100) as $i){ $a=$faker->randomElement($userIds); $b=$faker->randomElement($userIds); if($a==$b) continue; DB::table('friendships')->updateOrInsert(['user_id'=>$a,'friend_id'=>$b],['status'=>$faker->randomElement(['pending','accepted']),'created_at'=>now(),'updated_at'=>now()]); }
 foreach(range(1,100) as $i){ $a=$faker->randomElement($userIds); $b=$faker->randomElement($userIds); if($a==$b) continue; DB::table('follows')->updateOrInsert(['user_id'=>$a,'target_user_id'=>$b],['created_at'=>now(),'updated_at'=>now()]); }
 $clubIds=[]; foreach(range(1,10) as $i){ $clubId=DB::table('clubs')->insertGetId(['name'=>$faker->company().' Club','logo'=>null,'description'=>$faker->sentence(8),'owner_id'=>$faker->randomElement($userIds),'created_at'=>now(),'updated_at'=>now()]); $clubIds[]=$clubId; $members=$faker->randomElements($userIds, $faker->numberBetween(5,20)); foreach($members as $u){ DB::table('club_members')->updateOrInsert(['club_id'=>$clubId,'user_id'=>$u],['role'=>'member','created_at'=>now(),'updated_at'=>now()]); } }
 $eventIds=[]; foreach(range(1,20) as $i){ $start=$faker->dateTimeBetween('-10 days','+60 days'); $end=(clone $start)->modify('+'.rand(2,48).' hours'); $eventId=DB::table('events')->insertGetId(['title'=>'Соревнование #'.$i,'description'=>$faker->sentence(12),'starts_at'=>$start,'ends_at'=>$end,'region'=>$faker->randomElement(['RU-MOW','RU-SPE','RU-MO','RU-LO','RU-KR']),'creator_id'=>$faker->randomElement($userIds),'created_at'=>now(),'updated_at'=>now()]); $eventIds[]=$eventId; $subs=$faker->randomElements($userIds, $faker->numberBetween(5,30)); foreach($subs as $u){ DB::table('event_subscriptions')->updateOrInsert(['event_id'=>$eventId,'user_id'=>$u],['created_at'=>now(),'updated_at'=>now()]); } }
 $roomIds=[]; foreach(range(1,10) as $i){ $roomId=DB::table('chat_rooms')->insertGetId(['title'=>'Комната #'.$i,'is_group'=>true,'created_at'=>now(),'updated_at'=>now()]); $roomIds[]=$roomId; $members=$faker->randomElements($userIds, $faker->numberBetween(3,10)); foreach($members as $u){ DB::table('chat_room_users')->updateOrInsert(['room_id'=>$roomId,'user_id'=>$u],['created_at'=>now(),'updated_at'=>now()]); } foreach(range(1,50) as $m){ DB::table('chat_messages')->insert(['room_id'=>$roomId,'user_id'=>$faker->randomElement($members),'text'=>$faker->realText(40),'created_at'=>now()->subMinutes(rand(0,5000)),'updated_at'=>now()]); } }
 foreach(range(1,200) as $i){ DB::table('notifications')->insert(['user_id'=>$faker->randomElement($userIds),'type'=>$faker->randomElement(['like','comment','friend_request','event_invite','digest','system']),'data'=>json_encode(['msg'=>$faker->sentence(6)]),'is_read'=>$faker->boolean(30),'created_at'=>now()->subMinutes(rand(0,10000)),'updated_at'=>now()]); }
 } }
